import type { GenerationTask } from "./types";

const NOW = Date.now();
const minutesAgo = (m: number) => new Date(NOW - m * 60_000);
const secondsAgo = (s: number) => new Date(NOW - s * 1_000);

export const GENERATION_TASK_SEED: GenerationTask[] = [
  {
    id: "gt-1",
    type: "text",
    prompt: "Короткий питч стартапа в одно предложение",
    model: "GPT 5.2",
    status: "running",
    progress: 67,
    createdAt: secondsAgo(42),
    eta: 18,
    credits: 6,
  },
  {
    id: "gt-2",
    type: "video",
    prompt:
      "Кинематографичный трейлер: город в тумане, неоновые вывески, дождь",
    model: "Kling",
    status: "running",
    progress: 34,
    createdAt: minutesAgo(3),
    eta: 142,
    credits: 85,
  },
  {
    id: "gt-3",
    type: "image",
    prompt: "Кинематографичный портрет: воин на закате, песчаная буря",
    model: "Nano Banana",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(25),
    eta: 45,
    credits: 30,
    queuePosition: 1,
  },
  {
    id: "gt-4",
    type: "audio",
    prompt: "Lo-fi бит с дождём и мягким синтом, 90 BPM",
    model: "Suno",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(18),
    eta: 95,
    credits: 40,
    queuePosition: 2,
  },
  {
    id: "gt-5",
    type: "text",
    prompt: "Объясни ребёнку, что такое чёрная дыра",
    model: "Claude Sonnet 4.5",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(12),
    eta: 22,
    credits: 8,
    queuePosition: 3,
  },
  {
    id: "gt-6",
    type: "image",
    prompt: "Минималистичный логотип для кофейни, тёплые тона, векторный стиль",
    model: "Flux",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(12),
    eta: 12,
    credits: 25,
  },
  {
    id: "gt-7",
    type: "text",
    prompt: "Слоган для бренда тёплой одежды",
    model: "Gemini 2.5 Pro",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(28),
    eta: 22,
    credits: 6,
  },
  {
    id: "gt-8",
    type: "video",
    prompt: "Плавный облёт горного озера на рассвете, 4K",
    model: "Sora",
    status: "failed",
    progress: 58,
    createdAt: minutesAgo(45),
    error: "Превышено время ожидания",
    credits: 120,
  },
  {
    id: "gt-9",
    type: "image",
    prompt: "Фотореалистичный интерьер скандинавской гостиной с камином",
    model: "Midjourney",
    status: "failed",
    progress: 12,
    createdAt: minutesAgo(52),
    error: "Недостаточно кредитов",
    credits: 35,
  },
  {
    id: "gt-10",
    type: "audio",
    prompt: "Голос диктора для рекламного ролика, уверенный тон",
    model: "ElevenLabs",
    status: "canceled",
    progress: 23,
    createdAt: minutesAgo(8),
    credits: 15,
  },
];
